### PR TITLE
Introduce flags for setting worker options such as task poller counts and concurrent execution limits

### PR DESCRIPTION
**Pull request by aromanovich**
## What was changed
The following flags were added:
```
      --worker-max-concurrent-activity-execution-size int        Max concurrent activity execution size
      --worker-max-concurrent-activity-task-pollers int          Max concurrent activity task pollers
      --worker-max-concurrent-workflow-task-execution-size int   Max concurrent workflow task execution size
      --worker-max-concurrent-workflow-task-pollers int          Max concurrent workflow task pollers
```

## Why?
To be able to set up workers according to [the recommendations](https://docs.temporal.io/dev-guide/worker-performance#configuration).

### CODE REVIEW

**Review by bergundy — COMMENTED** [review]
Can you please add this to the Python worker as well? I can also do it if you wish.

**Comment by bergundy** [comment]
Thanks for the contribution!

**Comment by cretz** [comment]
I just merged your other PR, can you merge main back into this branch?

**Review by cretz — APPROVED** [review]

**Comment by aromanovich** [comment]
> I just merged your other PR, can you merge main back into this branch?

Done. The tests have failed seemingly due to a flap. The dev server keeps saying "Not enough hosts to serve the request" and doesn't respond — I have seen this happening on my laptop as well.

**Comment by cretz** [comment]
:+1: Rerunning CI. If/when it passes, we'll merge. Thanks for the PR!

**Comment by cretz** [comment]
Something is up with the server or how it's connecting with Python. We will need time to investigate this. I don't think it's related to this issue.

**Comment by aromanovich** [comment]
> Something is up with the server or how it's connecting with Python. We will need time to investigate this. I don't think it's related to this issue.

It was completely due to my mistake: https://github.com/temporalio/omes/pull/31/commits/c22a24e75c62b989896ee79e79bcf0af02ffa666

**Comment by cretz** [comment]
:+1: I merged main into your branch, if/when CI passes I can merge

**Comment by aromanovich** [comment]
> 👍 I merged main into your branch, if/when CI passes I can merge

Also https://github.com/temporalio/omes/pull/31 probably should be closed once we merge this.

**Pull request merged**
